cloud_function: add alarmMissingVAAs
wormhole-foundation/wormhole-dashboard pull request #120
Opened 2023-08-30 21:17 UTC by panoel

2023-08-31 17:22 UTC, bruce-riley commented on cloud_functions/src/alarmMissingVaas.ts
> +    txHash: msg.txHash,
Could you add the chainName here to make it easier for humans to understand?

2023-09-01 19:15 UTC, panoel commented on cloud_functions/src/alarmMissingVaas.ts
> +    txHash: msg.txHash,
That and more...

2023-09-05 16:05 UTC, evan-gray requested changes
good start, couple small things in the dashboard 🙂

2023-09-05 16:05 UTC, evan-gray commented on common/src/consts.ts
> +  33: {
This ID doesn't seem right. did you mean 3104

2023-09-05 16:05 UTC, evan-gray commented on dashboard/src/utils/consts.ts
> +  33: {
actually, should this whole thing just be imported from the consts `CHAIN_INFO_MAP`? 🤔

2023-09-05 19:40 UTC, panoel commented on dashboard/src/utils/consts.ts
> +  33: {
Put most of this in common/consts.ts and created new structure for icon images.

2023-09-06 14:15 UTC, merged