cloud_functions: don't alarm governed VAAs
wormhole-foundation/wormhole-dashboard pull request #135
Opened 2023-09-20 14:10 UTC by panoel

Grab the governed VAAs from the firestore governorStatus table.  Add filtering so that these VAAs don't get alarmed in slack.

2023-09-20 14:18 UTC, evan-gray requested changes
should be quicker to simply grab all the documents in the collection.

https://firebase.google.com/docs/firestore/query-data/get-data#node.js_6

2023-09-26 11:11 UTC, barnjamin approved these changes

2023-09-27 15:42 UTC, barnjamin approved these changes

2023-09-27 16:18 UTC, evan-gray requested changes

2023-09-27 16:18 UTC, evan-gray commented on cloud_functions/src/alarmMissingVaas.ts
> +  snapshot.forEach(async (doc) => {
I think you can't use an async method in a forEach. I don't think you need the async since you don't have any awaits. I've found a better habit is using 
```
for (const doc of snapshot) {
  // do stuff
  // you can even await stuff in here
}
```

2023-09-27 16:37 UTC, panoel commented on cloud_functions/src/alarmMissingVaas.ts
> +  snapshot.forEach(async (doc) => {
I stole this code from a different cloud_function.  We should probably change that one, too.
Fixed.

2023-09-27 17:04 UTC, evan-gray approved these changes

2023-09-27 18:17 UTC, merged