dashboard: update consts
wormhole-foundation/wormhole-dashboard pull request #191
Opened 2024-01-22 18:19 UTC by panoel

This PR does the following:
- removes karura from testnet watchers
- updates testnet endpoints shown on the dashboard for missed and signed VAAs in the monitor section
- testnet missing VAAs cloud function no longer alarms to slack.

2024-01-23 18:00 UTC, evan-gray requested changes
a few structure things that could lead to bugs in your react code

2024-01-23 18:00 UTC, evan-gray commented on dashboard/src/components/MainnetGovernor.tsx
> +                        alt={CHAIN_INFO_MAP[GetNetworkFromEnv()][chainId].name}
ditto: loop

2024-01-23 19:46 UTC, panoel commented on cloud_functions/src/alarmMissingVaas.ts
> +  const network: NETWORK = assertEnvironmentVariable('NETWORK') ? NETWORK.MAINNET : NETWORK.TESTNET;
Oops, missing the actual comparison.  Good catch.

2024-01-23 19:54 UTC, panoel commented on cloud_functions/src/alarmMissingVaas.ts
Fixed

2024-01-23 20:00 UTC, panoel commented on dashboard/src/components/Accountant.tsx
> +                        alt={CHAIN_INFO_MAP[GetNetworkFromEnv()][chainId].name}
Fixed.

2024-01-23 20:03 UTC, panoel commented on dashboard/src/components/Governor.tsx
> +          href={explorerTx(GetNetworkFromEnv(), chainInfo.chainId, txHash)}
Fixed

2024-01-23 20:05 UTC, panoel commented on dashboard/src/components/Governor.tsx
> +                        alt={CHAIN_INFO_MAP[GetNetworkFromEnv()][chainId].name}
Fixed

2024-01-23 20:08 UTC, panoel commented on dashboard/src/components/MainnetGovernor.tsx
> +                        alt={CHAIN_INFO_MAP[GetNetworkFromEnv()][chainId].name}
Fixed.

2024-01-24 22:36 UTC, panoel commented on dashboard/src/components/MainnetGovernor.tsx
> +      const network = GetNetworkFromEnv();
Fixed.

2024-01-24 22:37 UTC, panoel commented on dashboard/src/components/MainnetGovernor.tsx
> +      const network = GetNetworkFromEnv();
Fixed

2024-01-24 22:47 UTC, panoel commented on dashboard/src/components/Monitor.tsx
> +  const network: NETWORK = currentNetwork.env === 'mainnet' ? NETWORK.MAINNET : NETWORK.TESTNET;
Fixed.

2024-01-24 23:40 UTC, panoel commented on dashboard/src/components/MainnetGovernor.tsx
> +                        alt={CHAIN_INFO_MAP[GetNetworkFromEnv()][chainId].name}
Fixed

2024-01-24 23:41 UTC, panoel commented on dashboard/src/components/MainnetGovernor.tsx
> +                    alt={CHAIN_INFO_MAP[GetNetworkFromEnv()][chainId].name}
Check that the fix is what you were thinking.

2024-01-24 23:48 UTC, panoel commented on dashboard/src/utils/GetNetworkFromEnv.ts
> +  const { currentNetwork } = useNetworkContext();
Fixed

2024-01-25 15:39 UTC, evan-gray requested changes
getting close - main thing is that `as` doesn't make the data safe to use, it just overrides the type safety. would probably be best to get all of the backend code using the same helper coalesce that env var into the type

2024-01-25 15:39 UTC, evan-gray commented on cloud_functions/src/alarmMissingVaas.ts
> +const network: Environment = assertEnvironmentVariable('NETWORK').toLowerCase() as Environment;
Not sure this is safe to do - `as` will simply override the type, but it doesn't actually ensure that the value is one of those in environment. Might be worth a helper function in `consts.ts` that's like `coalesceToEnvironment` which does the `.toLowerCase()` and throws if it's not one of `'mainnet', 'testnet', 'devnet'`

2024-01-25 15:39 UTC, evan-gray commented on dashboard/src/components/MainnetGovernor.tsx
> +                    alt={CHAIN_INFO_MAP[useCurrentEnvironment()][chainId].name}
does react not complain about using a hook here? I'd think this would need to be in a component.

2024-01-25 15:39 UTC, evan-gray commented on dashboard/src/components/ExplorerURL.tsx
> +export function ExplorerURL({ chain, rawTxHash }: { chain: number; rawTxHash: string }) {
what type of url is this? maybe `ExplorerAssetURL` would be more descriptive. similarly, it looks like the parameter is an `hexAddress` not a `rawTxHash`.

2024-01-25 15:39 UTC, evan-gray commented on watcher/scripts/backfillNear.ts
> +  const network: Environment = assertEnvironmentVariable('NETWORK').toLowerCase() as Environment;
same comment as the other `as` - not safe, should use the helper

2024-01-25 15:39 UTC, evan-gray commented on watcher/src/utils/environment.ts
> +  return assertEnvironmentVariable('NETWORK').toLowerCase() as Environment;
ditto, not safe

2024-01-25 16:13 UTC, panoel commented on cloud_functions/src/alarmMissingVaas.ts
> +const network: Environment = assertEnvironmentVariable('NETWORK').toLowerCase() as Environment;
Fixed.

2024-01-25 16:15 UTC, panoel commented on cloud_functions/src/alarmMissingVaas.ts
> +const network: Environment = assertEnvironmentVariable('NETWORK').toLowerCase() as Environment;
Fixed

2024-01-25 17:50 UTC, panoel commented on watcher/src/utils/environment.ts
> +  return assertEnvironmentVariable('NETWORK').toLowerCase() as Environment;
Removed.

2024-01-25 17:55 UTC, panoel commented on watcher/scripts/backfillNear.ts
> +  const network: Environment = assertEnvironmentVariable('NETWORK').toLowerCase() as Environment;
Fixed

2024-01-25 17:55 UTC, panoel commented on watcher/src/utils/environment.ts
> +  return assertEnvironmentVariable('NETWORK').toLowerCase() as Environment;
Fixed

2024-01-25 19:22 UTC, panoel commented on dashboard/src/components/ExplorerURL.tsx
> +export function ExplorerURL({ chain, rawTxHash }: { chain: number; rawTxHash: string }) {
Fixed

2024-01-25 21:09 UTC, evan-gray requested changes
I think just missed one spot and maybe clean up that function name and then should be good? 🤞

2024-01-25 21:09 UTC, evan-gray commented on common/src/consts.ts
> +export function coalesceToEnvironment(): Environment {
ah, this wasn't what I expected but this is probably better. should we just call this `getEnvironment` and move it to utils? :grimacing:

2024-01-25 21:17 UTC, panoel commented on cloud_functions/src/alarmMissingVaas.ts
> +  const network: NETWORK = assertEnvironmentVariable('NETWORK') ? NETWORK.MAINNET : NETWORK.TESTNET;
This got fixed when I removed the type NETWORK

2024-01-25 21:20 UTC, panoel commented on watcher/scripts/backfillNear.ts
> +  const network: Environment = assertEnvironmentVariable('NETWORK').toLowerCase() as Environment;
Doh.

2024-01-25 21:29 UTC, panoel commented on common/src/consts.ts
> +export function coalesceToEnvironment(): Environment {
Moved

2024-01-25 21:41 UTC, evan-gray approved these changes

2024-01-25 21:47 UTC, panoel commented on dashboard/src/components/Governor.tsx
> +      const network = GetNetworkFromEnv();
Fixed

2024-01-25 21:47 UTC, panoel commented on dashboard/src/components/Governor.tsx
> +      const network = GetNetworkFromEnv();
Fixed

2024-01-25 21:48 UTC, merged