common: move to sdk v2
wormhole-foundation/wormhole-dashboard pull request #243
Opened 2024-04-01 19:49 UTC by panoel

2024-04-01 20:17 UTC, barnjamin commented on cloud_functions/src/processVaa.ts
> +    const chainId = Number(chain) as ChainId;
`toChainId](https://github.com/wormhole-foundation/wormhole-sdk-ts/blob/main/core/base/src/constants/chains.ts#L86) should parse and set the type

2024-04-01 20:17 UTC, barnjamin commented on common/src/consts.ts
>        name: 'solana',
do these names need to change?

2024-04-01 20:17 UTC, barnjamin commented on common/src/consts.ts
>        endpointUrl: process.env.REACT_APP_SOLANA_RPC || 'https://api.mainnet-beta.solana.com',
can get this from rpc consts as well

2024-04-01 20:27 UTC, bingyuyap commented on watcher/src/watchers/InjectiveExplorerWatcher.ts
> +import { CONTRACTS, ChainName } from '@certusone/wormhole-sdk/lib/cjs/utils/consts';
There should be a method `getContracts` from the `sdk-definitions` package that serves the same purpose. Since we are trying to move entire to `sdkv2` it might be worth updating this as well. You can check out [`getContracts`](https://github.com/wormhole-foundation/connect-sdk/blob/sdkv2/core/definitions/src/contracts.ts#L24) to see if this is what we want. 

```ts
import { getContracts } from '@wormhole-foundation/sdk-definitions';

// line 52
const coreAddress = getContracts(this.network, this.chain).coreBridge;
```

The thing about using this is that the `network` param in `getContracts`  uses `["Mainnet", "Testnet", "Devnet"]` but our repo uses `'mainnet' | 'testnet' | 'devnet'`. We can do this in another PR if you want.

2024-04-01 20:29 UTC, bingyuyap submitted a review, later dismissed
Everything looks good to me. Just one comment about using `getContracts` from `@wormhole-foundation/sdk-definitions` instead of `CONTRACTS` from the `certusone` sdk. 

Appreciate the work!

2024-04-02 17:38 UTC, evan-gray commented on cloud_functions/src/processVaa.ts
> +    const chainId = Number(chain) as ChainId;
can follow up when the rest of the methods are switched over

2024-04-02 17:44 UTC, evan-gray commented on common/src/consts.ts
>        name: 'solana',
removed

2024-04-02 17:44 UTC, evan-gray commented on common/src/consts.ts
>        endpointUrl: process.env.REACT_APP_SOLANA_RPC || 'https://api.mainnet-beta.solana.com',
removed

2024-04-02 17:55 UTC, evan-gray commented on watcher/src/watchers/InjectiveExplorerWatcher.ts
> +import { CONTRACTS, ChainName } from '@certusone/wormhole-sdk/lib/cjs/utils/consts';
let's tackle the watcher in a separate PR

2024-04-02 17:56 UTC, evan-gray approved these changes

2024-04-02 17:57 UTC, evan-gray commented
approving to get this change which replaces the deprecated sdk for the new one in `common` and `dashboard` only

2024-04-02 18:05 UTC, evan-gray requested changes
ah, wait `toChain` isn't safe to use in all these places as it could throw

2024-04-02 18:06 UTC, barnjamin approved these changes

2024-04-02 18:30 UTC, evan-gray approved these changes
fixed `toChain` usage

2024-04-02 18:42 UTC, merged