Bing/dashboard ntt capacity
wormhole-foundation/wormhole-dashboard pull request #255
Opened 2024-04-06 22:44 UTC by bingyuyap

This PR adds the inbound and outbound capacity for the supported chains onto the dashboard. 

2 issues:
- Waiting for error on Solana NTT SDK to be investigated 
- Outbound Capacity column shifts to the right very slightly, didn't fix because I don't to touch too much of the frontend code 

![image](https://github.com/wormhole-foundation/wormhole-dashboard/assets/62840970/a9f46c4f-8e4f-41af-8b90-03b12cf20f79)

2024-04-07 01:30 UTC, evan-gray requested changes
Good start. In addition to the comments, one organizational thing seems incorrect - this will be used to monitor multiple networks of NTT tokens so the rate limits should probably be organized and displayed that way.

2024-04-07 01:30 UTC, evan-gray commented on common/src/consts.ts
If these are only relevant to the dashboard, let’s keep them in the dashboard folder for now.

2024-04-07 01:30 UTC, evan-gray commented on dashboard/package.json
> +    "ethers": "^6.11.1",
Can we avoid the ethers dependency? We’ve done well avoiding it this far.

2024-04-07 01:30 UTC, evan-gray commented on dashboard/src/components/LookerRateLimits.tsx
> +export function LookerRateLimits() {
Why is this called “Looker” rate limits? It doesn’t have anything to do with Looker. Maybe NTTRateLimits would be more apt.

2024-04-07 01:30 UTC, evan-gray commented on dashboard/src/hooks/useRateLimits.ts
> +      setRateLimits(limits);
This effect does not handle when it’s cancelled which can lead to memory leaks (and a warning from react). See the other hooks for examples. Also probably worth auto refreshing every minute or so like the others.

2024-04-07 11:05 UTC, bingyuyap commented on dashboard/package.json
> +    "ethers": "^6.11.1",
I'm adding the `tokenDecimal` call to the SDK, finding out whether Solana has the same call before doing that

2024-04-07 14:47 UTC, bingyuyap commented on dashboard/src/hooks/useRateLimits.ts
> +      setRateLimits(limits);
I hope I did it right 🤣

2024-04-07 18:32 UTC, bingyuyap commented on dashboard/package.json
> +    "ethers": "^6.11.1",
removed, everything is axios now

2024-04-12 15:25 UTC, evan-gray commented on dashboard/src/hooks/useRateLimits.ts
> +      setRateLimits(limits);
you should also check `cancelled` right before calling set since you're awaiting an async call above, it could have been cancelled between your initial check and here.

2024-04-12 15:26 UTC, panoel commented on dashboard/src/components/NTTMetrics.tsx
> +      <NTTRateLimits />
Will you be adding NTTRateLimits to the mainnet metrics?

2024-04-12 15:28 UTC, panoel commented on dashboard/src/utils/consts.ts
> +export const NTT_MANAGER_CONTRACT: {
Aren't these in the NTTconsts.ts file?

2024-04-12 15:30 UTC, panoel commented on dashboard/src/utils/consts.ts
> +  [key in Network]: { [tokenName: string]: { [key in Chain]?: string } };
Does it make sense to do a [tokenAddr, tokenName] here?  Will the tokenName be used outside of the embeded looker graphic?

2024-04-12 15:57 UTC, panoel commented on dashboard/src/utils/consts.ts
> +export const NTT_MANAGER_CONTRACT: {
Should we pull some of this into a common/NttConsts.ts file and pull the files out of watcher/ too?

2024-04-12 16:01 UTC, panoel commented on dashboard/src/utils/evmNttHelpers.ts
> +
```suggestion
  const hashArray: Uint8Array = keccak256(methodSignature);
```

2024-04-12 16:07 UTC, panoel commented on dashboard/src/utils/evmNttHelpers.ts
> +  const payload = {
Since this is common code for the next 3 functions, too bad you can't have a function that takes (rpc, contractAddr, data) and returns a response.

2024-04-12 20:04 UTC, bingyuyap commented on dashboard/src/components/NTTMetrics.tsx
> +      <NTTRateLimits />
I should!

2024-04-12 20:04 UTC, bingyuyap commented on dashboard/src/hooks/useRateLimits.ts
> +      setRateLimits(limits);
Will add

2024-04-12 20:07 UTC, bingyuyap commented on dashboard/src/utils/consts.ts
> +  [key in Network]: { [tokenName: string]: { [key in Chain]?: string } };
Do you mean like this: 

```ts
export const NTT_TOKENS: TokenAddresses = {
  Mainnet: {},
  Testnet: {
    Solana: {
      '87r5ZS91Q2pQbFTvvneqs7y7mbtegtqMt4LDAS4g23Ax': 'TestToken',
    },
    Sepolia: {
      '0x1d30E78B7C7fbbcef87ae6e97B5389b2e470CA4a': 'TestToken',
    },
    ArbitrumSepolia: {
      '0x84A1Cb660B19eB0063EE5FD377eC14AAe3364d74': 'TestToken',
    },
    BaseSepolia: {
      '0x7f430D4e7939D994C0955A01FC75D9DE33F12D11': 'TestToken',
    },
    OptimismSepolia: {
      '0x0e15979a7a1eFAEf20312CA45A59eb141bF7E340': 'TestToken',
    },
  },
  Devnet: {},
};
```

The token name will be displayed in the table below the looker, if that's what you are asking about

2024-04-12 20:09 UTC, bingyuyap commented on dashboard/src/utils/consts.ts
> +export const NTT_MANAGER_CONTRACT: {
The `NTTConsts.ts` file supports a different structure, but I can update the logic to conform with that

2024-04-12 20:10 UTC, bingyuyap commented on dashboard/src/utils/evmNttHelpers.ts
> +  const payload = {
I'll try to modularize that logic

2024-04-12 22:23 UTC, bingyuyap commented on dashboard/src/utils/consts.ts
> +export const NTT_MANAGER_CONTRACT: {
Added the const file `common/src/nttConsts.ts` with a function to convert to the data structure that is usually used in the watchers

2024-04-15 17:37 UTC, evan-gray requested changes

2024-04-15 17:37 UTC, evan-gray commented on common/src/nttConsts.ts
> +export function SUPPORTED_CHAINS(network: Network, token: string): Chain[] {
this not being prefixed with `NTT_` makes me a little nervous given that this file is re-exported

2024-04-15 17:37 UTC, evan-gray commented on common/src/nttConsts.ts
> +type NTTContract = {
should these types be exported?

2024-04-15 17:37 UTC, evan-gray commented on common/src/nttConsts.ts
> +  return Object.keys(NTT_MANAGER_CONTRACT[network][token]) as Chain[];
would be nice if there were a cleaner way to do this without the `as`

2024-04-15 17:37 UTC, evan-gray commented on dashboard/src/components/NTTRateLimits.tsx
> +        ) : null}{' '}
feel like this could use an indent here for when there isn't a dropdown arrow, else the indentation is a bit odd

2024-04-15 17:37 UTC, evan-gray commented on dashboard/src/utils/nttHelpers.ts
> +  const rpcAddress = rpc.rpcAddress(network.name as SdkNetwork, chain);
all of these rpc calls could have been batched into a single request. this might be fine for now but should be reconsidered as the list of tokens grows

2024-04-15 17:37 UTC, evan-gray commented on watcher/src/watchers/NTTSolanaWatcher.ts
> +import { NTT_MANAGER_CONTRACT_ARRAY } from '../../../common/src/nttConsts';
this import should be from the package, not the file path

2024-04-15 17:37 UTC, evan-gray commented on watcher/src/watchers/NTTWatcher.ts
> +import { NTT_MANAGER_CONTRACT_ARRAY } from '../../../common/src/nttConsts';
this import should be from the package, not the file path

2024-04-15 17:37 UTC, evan-gray commented on dashboard/src/utils/nttHelpers.ts
> +} from '@wormhole-foundation/wormhole-monitor-common/dist/nttConsts';
should this use the top level export instead?

2024-04-15 22:04 UTC, bingyuyap commented on common/src/nttConsts.ts
> +  return Object.keys(NTT_MANAGER_CONTRACT[network][token]) as Chain[];
I think `Object.keys` inherently return `string[]`. Another way would be something like

```ts
export function NTT_SUPPORTED_CHAINS(network: Network, token: string): Chain[] {
  const contractDetails = NTT_MANAGER_CONTRACT[network][token];
  if (!contractDetails) {
    return [];
  }

// chains imported from sdk-base
  return chains.filter((chain) => chain in contractDetails);
}
```

2024-04-15 22:10 UTC, bingyuyap commented on dashboard/src/utils/nttHelpers.ts
> +  const rpcAddress = rpc.rpcAddress(network.name as SdkNetwork, chain);
let's do this in the coming pull request

2024-04-15 22:37 UTC, bingyuyap commented on dashboard/src/components/NTTRateLimits.tsx
> +        ) : null}{' '}
added!

2024-04-15 22:37 UTC, bingyuyap commented on watcher/src/watchers/NTTSolanaWatcher.ts
> +import { NTT_MANAGER_CONTRACT_ARRAY } from '../../../common/src/nttConsts';
changed

2024-04-15 22:37 UTC, bingyuyap commented on watcher/src/watchers/NTTWatcher.ts
> +import { NTT_MANAGER_CONTRACT_ARRAY } from '../../../common/src/nttConsts';
changed

2024-04-15 22:37 UTC, bingyuyap commented on dashboard/src/utils/nttHelpers.ts
> +} from '@wormhole-foundation/wormhole-monitor-common/dist/nttConsts';
changed

2024-04-16 22:08 UTC, evan-gray approved these changes

2024-04-16 22:09 UTC, merged