common,cloud_function: add getMissThreshold()
wormhole-foundation/wormhole-dashboard pull request #316
Opened 2024-06-06 19:51 UTC by panoel

2024-06-06 20:37 UTC, bingyuyap commented on common/src/consts.ts
> +  const missDate = new Date(date);
since `data` is already type of `Date` do we still need to do `new Date(date)`?

2024-06-06 20:41 UTC, bingyuyap commented on common/src/consts.ts
> +export function getMissThreshold(date: Date, chainId: ChainId): string {
I wonder if it would be easier too have this function to accept types `(number | string | Chain | ChainId)` and then do a conditional conversion to `ChainId` in this function. 

Like this we get a more versatile function and prevent having to write `toChainId(Number(chain))` everywhere.

2024-06-06 20:41 UTC, bingyuyap approved these changes

2024-06-06 20:42 UTC, bingyuyap approved these changes
Need to format these files
```
[warn] common/src/consts.ts
[warn] dashboard/src/components/Monitor.tsx
[warn] watcher/scripts/solanaMissedMessageAccounts.ts
```

2024-06-06 21:18 UTC, panoel commented on common/src/consts.ts
> +  const missDate = new Date(date);
No, we do not.

2024-06-06 21:19 UTC, panoel commented on common/src/consts.ts
> +export function getMissThreshold(date: Date, chainId: ChainId): string {
Do we *really* want to make life easier for people?

2024-06-06 21:22 UTC, bingyuyap commented on common/src/consts.ts
> +export function getMissThreshold(date: Date, chainId: ChainId): string {
It's fine with me either way, we can update the function if and when we actually need the versatility

2024-06-06 21:46 UTC, panoel commented on common/src/consts.ts
> +export function getMissThreshold(date: Date, chainId: ChainId): string {
I made the change...

2024-06-06 21:49 UTC, bingyuyap commented on common/src/consts.ts
> +export function getMissThreshold(date: Date, chainId: ChainId): string {
Thanks! Let me do a last check

2024-06-06 21:55 UTC, bingyuyap submitted a review, later dismissed

2024-06-07 14:37 UTC, evan-gray requested changes
The review comments might come out of order, but essentially everywhere you used `toChainId` is likely unsafe. It would throw, crashing the given code, when a new chain is added but the corresponding sdk has not been bumped yet (or the front-end deployed after rthe backend, etc). I would revert all of those changes and simply use the number of the chain in the `getMissThreshold` code. It should still be find to compare `chainId === toChainId('Scroll')` when `chainId` is a number.

2024-06-07 14:37 UTC, evan-gray commented on common/src/consts.ts
>  export const MISS_THRESHOLD_LABEL = '40 minutes';
good idea :+1:

2024-06-07 14:37 UTC, evan-gray commented on common/src/consts.ts
> +    chainId = toChainId(Number(chainish));
I don't think we should do this - if something does not get an sdk version bump and one of these numbers is not in the list of chain ids, this will throw! It would probably be easier to just `Number(chainish)` when it's a string and not care if it's NaN because it will get the default anyway.

2024-06-07 14:37 UTC, evan-gray commented on dashboard/src/components/Monitor.tsx
> +                (message) => message.timestamp < getMissThreshold(now, toChainId(Number(chain)))
Don't use `toChainId` here, as explained above, the whole front-end may crash if/when it throws. Just pass `chain` since you made it handle strings (which is great btw)

2024-06-07 14:37 UTC, evan-gray commented on dashboard/src/components/Monitor.tsx
> +          href={explorerBlock(network, toChainId(Number(chain)), message.block.toString())}
ditto, probably not safe - might want to revisit `explorerBlock` later

2024-06-07 14:37 UTC, evan-gray commented on dashboard/src/components/Monitor.tsx
> +            href={explorerTx(network, toChainId(Number(chain)), message.txHash)}
ditto

2024-06-07 14:37 UTC, evan-gray commented on dashboard/src/components/Monitor.tsx
> +              header={`${chainIdToChain.get(toChainId(Number(chain)))} (${chain}) - ${
same, `toChainId` is not safe here

2024-06-07 14:37 UTC, evan-gray commented on dashboard/src/components/Monitor.tsx
> +            : { ...counts, [toChainId(Number(chain))]: filteredMisses.length };
same

2024-06-07 14:37 UTC, evan-gray commented on dashboard/src/components/Monitor.tsx
> +                          {chainIdToChain.get(toChainId(Number(chain)))} ({chain})
likely same for this and below

2024-06-07 15:43 UTC, panoel commented on common/src/consts.ts
> +    chainId = toChainId(Number(chainish));
I don't feel comfortable with this because if it is a string, it can be '1' or 'Solana'.  That is not handled by toChainId().  But I have a solution that I believe addresses your concerns.

2024-06-07 15:47 UTC, panoel commented on dashboard/src/components/Monitor.tsx
> +          href={explorerBlock(network, toChainId(Number(chain)), message.block.toString())}
Changed back.

2024-06-07 15:48 UTC, panoel commented on dashboard/src/components/Monitor.tsx
> +                (message) => message.timestamp < getMissThreshold(now, toChainId(Number(chain)))
Fixed.

2024-06-07 15:49 UTC, panoel commented on dashboard/src/components/Monitor.tsx
> +              header={`${chainIdToChain.get(toChainId(Number(chain)))} (${chain}) - ${
Changed back.

2024-06-07 15:50 UTC, panoel commented on dashboard/src/components/Monitor.tsx
> +                          {chainIdToChain.get(toChainId(Number(chain)))} ({chain})
Changed back

2024-06-07 15:51 UTC, panoel commented on dashboard/src/components/Monitor.tsx
> +            : { ...counts, [toChainId(Number(chain))]: filteredMisses.length };
Changed back

2024-06-07 16:27 UTC, evan-gray approved these changes

2024-06-07 16:30 UTC, evan-gray commented on common/src/consts.ts
> +    chainId = toChainId(Number(chainish));
Ah, wasn't considering `Solana` case. Looks good now though, thanks!

2024-06-07 16:43 UTC, merged