Use the new p2p.Run API
wormhole-foundation/wormhole-dashboard pull request #329
Opened 2024-06-26 16:02 UTC by bruce-riley

This modifies the fly and other gossip listening tools to use the new `p2p.Run` API.

It also removes the hardcoded bootstrap parameters in favor of the ones defined in `node/pkg/p2p/network_consts.go`.

2024-08-20 16:40 UTC, evan-gray reviewed
repeated the comments about the unused components just to keep track. overall the less code is great, mostly concerned about `fly/main.go` where there doesn't appear to be a way to weak the gossip params anymore.

2024-08-20 16:40 UTC, evan-gray commented on fly/go.mod
> +replace github.com/certusone/wormhole/node v0.0.0-20240507160701-1c858d355869 => github.com/wormhole-foundation/wormhole/node v0.0.0-20240816195349-530fea1b066a
could this just update the entry on line 11? curious why this wasn't there before if not.

2024-08-21 15:39 UTC, evan-gray requested changes
nice. one small change please :)

2024-08-21 15:39 UTC, evan-gray commented on fly/cmd/prom_gossip/main.go
> +					addr := "0x" + string(hex.EncodeToString(batch.Msg.Addr))
optimization, but probably only have to do this (the `addr`, `idx` and `name`) once per batch message right? so can move this above the `for`. also this is missing the improvement from the previous PR to check `found` before using the name.

2024-08-21 15:49 UTC, evan-gray commented on fly/cmd/prom_gossip/main.go
> +					gossipByType.WithLabelValues("observation").Inc()
can we move this above the for loop and call it `batch_observation`

2024-08-21 17:08 UTC, panoel commented on fly/cmd/observation_stats/main.go
> +						// logger.Warn("observation", zap.String("id",o.MessageId), zap.String("addr",ga))
Probably don't need this comment anymore

2024-08-21 17:08 UTC, panoel commented on fly/cmd/observation_stats/main.go
>  					// logger.Warn("observation", zap.String("id",o.MessageId), zap.String("addr",ga))
Probably don't need this comment anymore.

2024-08-21 17:15 UTC, panoel approved these changes

2024-08-21 17:16 UTC, bingyuyap commented on fly/cmd/heartbeats/main.go
> +			case o := <-obsvC: // TODO: Rip out this code once we cut over to batching.
Do we still need this? Seems like batching is already added in this PR

2024-08-21 17:24 UTC, bingyuyap commented on fly/cmd/historical_uptime/main.go
> +			case o := <-obsvC: // TODO: Rip out this code once we cut over to batching.
we can remove this comment as well since batching is added in this PR

2024-08-21 17:30 UTC, bingyuyap commented on fly/cmd/observation_stats/main.go
> +	gst := common.NewGuardianSetState(nil)
Will this work the same if there is no heartbeat channel?

2024-08-21 17:31 UTC, bingyuyap commented on fly/cmd/prom_gossip/main.go
> +			case o := <-obsvC: // TODO: Rip out this code once we cut over to batching.
We can remove this as well

2024-08-21 17:32 UTC, bingyuyap commented on fly/cmd/track_gossip/main.go
>  	// TODO: pass in config instead of hard-coding it
remove this as well since its not hardcoded

2024-08-21 17:34 UTC, bingyuyap commented on fly/cmd/prom_gossip/main.go
> +						uniqueObservationsCounter.Inc()
if uniqueObs doesn't exist at first, do we need to increment the count to 1 regardless? or would it be 0 at first

2024-08-21 17:39 UTC, bingyuyap reviewed
Just some questions that I'm unclear with, also commented on parts that can be removed like single observations and comments due to the batch observation addition

2024-08-21 17:39 UTC, bingyuyap commented on fly/cmd/track_gossip/main.go
> +			case <-obsvC: // TODO: Rip out this code once we cut over to batching.
This TODO can be removed as well

2024-08-21 17:39 UTC, bingyuyap commented on fly/cmd/track_pyth/main.go
>  	// TODO: pass in config instead of hard-coding it
Reminder to remove this comment

2024-08-21 17:39 UTC, bingyuyap commented on fly/cmd/track_pyth/main.go
> +			case m := <-obsvC: // TODO: Rip out this code once we cut over to batching.
We can remove this since we have batching now

2024-08-21 18:03 UTC, bruce-riley commented on fly/cmd/heartbeats/main.go
> +			case o := <-obsvC: // TODO: Rip out this code once we cut over to batching.
Yeah, we still need this. Although batching is supported by the code, the network has not cut over to it yet.

2024-08-22 14:27 UTC, bruce-riley commented on fly/cmd/heartbeats/main.go
> +							obsvRateTable.AppendRow(table.Row{i, obsvRateRows[int(i)].guardianName, obsvRateRows[int(i)].obsvCount, obsvRateRows[uint(i)].percents[0], obsvRateRows[uint(i)].percents[1], obsvRateRows[uint(
Don't know, but I broke up the line to make you happy. 😁

2024-08-22 14:27 UTC, bruce-riley commented on fly/cmd/historical_uptime/main.go
> +			case o := <-obsvC: // TODO: Rip out this code once we cut over to batching.
No, same reason as above.

2024-08-22 14:28 UTC, bingyuyap commented on fly/cmd/heartbeats/main.go
> +							obsvRateTable.AppendRow(table.Row{i, obsvRateRows[int(i)].guardianName, obsvRateRows[int(i)].obsvCount, obsvRateRows[uint(i)].percents[0], obsvRateRows[uint(i)].percents[1], obsvRateRows[uint(
Haha thanks Bruce!

2024-08-22 14:30 UTC, bruce-riley commented on fly/cmd/observation_stats/main.go
>  	// TODO: pass in config instead of hard-coding it
No, I think the TODO is still valid. If someone ever wants to use this particular tool again, they can make that change if they want. That's beyond the scope of this PR.

2024-08-22 14:33 UTC, bruce-riley commented on fly/cmd/observation_stats/main.go
> +	gst := common.NewGuardianSetState(nil)
Yeah, this is a more efficient way to ignore heartbeats. We won't won't even get them, rather than getting them and just throwing them away.

2024-08-22 14:34 UTC, bruce-riley commented on fly/cmd/prom_gossip/main.go
> +			case o := <-obsvC: // TODO: Rip out this code once we cut over to batching.
No, same reason as above.

2024-08-22 14:35 UTC, bruce-riley commented on fly/cmd/track_gossip/main.go
>  	// TODO: pass in config instead of hard-coding it
No, same reason as above. If someone wants to use this tool again, they may want to pass in parameters. But that's beyond the scope of this PR.

2024-08-22 14:41 UTC, bruce-riley commented on fly/cmd/track_gossip/main.go
> +			case <-obsvC: // TODO: Rip out this code once we cut over to batching.
No, same comment as above.

2024-08-22 14:41 UTC, bruce-riley commented on fly/cmd/track_pyth/main.go
>  	// TODO: pass in config instead of hard-coding it
No, same comment as above.

2024-08-22 14:42 UTC, bruce-riley commented on fly/cmd/track_pyth/main.go
> +			case m := <-obsvC: // TODO: Rip out this code once we cut over to batching.
No, same comment as above.

2024-08-22 16:41 UTC, bingyuyap approved these changes

2024-08-22 16:43 UTC, evan-gray approved these changes

2024-08-22 16:57 UTC, merged