cloud_functions/dashboard: add getGuardianSetInfo cf
wormhole-foundation/wormhole-dashboard pull request #336
Opened 2024-07-17 22:10 UTC by panoel

2024-07-23 18:42 UTC, evan-gray requested changes
Overall good, couple small things 🙂

2024-07-23 18:42 UTC, evan-gray commented on cloud_functions/package.json
> +    "@wormhole-foundation/sdk-base": "^0.8.0",
Leaving this comment for posterity - this was required as the cloud_functions are currently deployed with `pack`ed versions of their siblings and does not include the workspace package lock. In this circumstance, npm was choosing an older sdk as the direct `node_modules` dependency when we wanted the version used by `database` and explicitly defined by the workspace.

2024-07-23 18:42 UTC, evan-gray commented on cloud_functions/src/getGuardianSetInfo.ts
> +        guardianSetIndex: BigInt(doc.data().guardianSetIndex),
could we not convert this to BigInt here so it doesn't have to be converted back on line 25?

2024-07-23 18:42 UTC, evan-gray commented on common/src/consts.ts
> +  guardianSetIndex: bigint;
akin to the previous comment, is it any easier if this is just a string?

2024-07-23 18:42 UTC, evan-gray commented on dashboard/src/hooks/useGetGuardianSet.ts
> +  console.log('Calling useGetGuardianSet with chain:', chain, 'and address:', address);
should we limit this method back to simply fetching the guardian set from eth since that's all it's used for now?

2024-07-23 18:42 UTC, evan-gray commented on dashboard/tsconfig.json
> +  "include": ["src", "../common/src/queryContractSmart.ts"]
this shouldn't be needed if properly importing from the package.

2024-07-23 18:42 UTC, evan-gray commented on dashboard/src/components/Contracts.tsx
> +      setGuardianSetInfoByChain(data);
This is potentially unsafe (memory leak) to set state after a component is destroyed - this can happen when this user navigates away while the request is outstanding. Check the other hooks for examples of how to set and check a `cancelled` variable. 

Also probably worth moving this to a hook like `useGetGuardianSetInfoByChain` in `hooks`.

2024-07-23 19:18 UTC, panoel commented on cloud_functions/package.json
> +    "@wormhole-foundation/sdk-base": "^0.8.0",
Added comment

2024-07-23 19:21 UTC, panoel commented on dashboard/tsconfig.json
> +  "include": ["src", "../common/src/queryContractSmart.ts"]
Removed.

2024-07-23 19:32 UTC, panoel commented on cloud_functions/src/getGuardianSetInfo.ts
> +        guardianSetIndex: BigInt(doc.data().guardianSetIndex),
Converted everything to string

2024-07-23 20:44 UTC, panoel commented on dashboard/src/hooks/useGetGuardianSet.ts
> +  console.log('Calling useGetGuardianSet with chain:', chain, 'and address:', address);
Changed.

2024-07-24 14:00 UTC, panoel commented on dashboard/src/components/Contracts.tsx
> +      setGuardianSetInfoByChain(data);
Moved to a hook.

2024-07-24 15:57 UTC, evan-gray approved these changes

2024-07-24 15:58 UTC, merged