watcher: mock Base tests
wormhole-foundation/wormhole-dashboard pull request #346
Opened 2024-08-02 17:18 UTC by panoel

2024-08-02 18:04 UTC, evan-gray requested changes
Might be worth trying a slightly more explicit, yet slightly more tedious approach. Also a couple quick signature fixes.

2024-08-02 18:04 UTC, evan-gray commented on watcher/src/watchers/__tests__/BaseWatcher.test.ts
> +      if (config) {
only downside is having to figure it out with `console.log(data, dataHash)` the first time around and it being a little less obvious what is being pulled.

2024-08-02 18:04 UTC, evan-gray commented on watcher/src/watchers/__tests__/BaseWatcher.test.ts
> +jest.mock('axios', () => {
probably worth moving this to `setup-jest.ts` so it's only in the one place.

2024-08-02 18:11 UTC, panoel commented on watcher/src/watchers/__tests__/BaseWatcher.test.ts
> +      // console.log('post retval', stringify(retval));
Fixed

2024-08-02 18:12 UTC, panoel commented on watcher/src/watchers/__tests__/BaseWatcher.test.ts
> +    post: jest.fn(async (url: string, config?: any) => {
Fixed

2024-08-02 18:19 UTC, panoel commented on watcher/src/watchers/__tests__/BaseWatcher.test.ts
> +      if (config) {
Won't this, also, apply to the getting latest block?

2024-08-02 18:28 UTC, panoel commented on watcher/src/watchers/__tests__/BaseWatcher.test.ts
> +      if (config) {
Changed

2024-08-02 18:34 UTC, panoel commented on watcher/src/watchers/__tests__/BaseWatcher.test.ts
> +jest.mock('axios', () => {
Moved

2024-08-02 19:20 UTC, evan-gray commented on watcher/src/watchers/__tests__/BaseWatcher.test.ts
> +      if (config) {
only what exists in the folder :+1:

2024-08-02 19:21 UTC, evan-gray commented on watcher/setup-jest.ts
> +        return JSON.parse(readFileSync(mockDataPath, 'utf8'));
can this store and return just the data or does that not work?
e.g. the `return { data: JSON.parse(readFileSync(mockDataPath, 'utf8')) };` like above

2024-08-02 19:28 UTC, evan-gray requested changes
Nice cleanup. Just one more nit, probably don't need to store the whole axios object.

2024-08-03 21:02 UTC, panoel commented on watcher/setup-jest.ts
> +        return JSON.parse(readFileSync(mockDataPath, 'utf8'));
Fixed.

2024-08-04 02:16 UTC, evan-gray approved these changes
Thanks!

2024-08-04 02:17 UTC, merged