watcher: make near archive watcher work
wormhole-foundation/wormhole-dashboard pull request #390
Opened 2024-11-20 23:08 UTC by panoel

2024-11-25 21:46 UTC, evan-gray requested changes

2024-11-25 21:46 UTC, evan-gray commented on watcher/src/watchers/__tests__/parseVaa.test.ts
> +// import {
this file is new, but why is there so much commented out / unused stuff in here?

2024-11-25 21:46 UTC, evan-gray commented on watcher/src/watchers/AlgorandWatcher.ts
> +    return { vaasByBlock, optionalBlockHeight: undefined };
simply omit `optionalBlockHeight`

```suggestion
    return { vaasByBlock };
```

2024-11-25 21:46 UTC, evan-gray commented on watcher/src/watchers/AptosWatcher.ts
> +    return { vaasByBlock, optionalBlockHeight: undefined };
ditto for this and the rest

2024-11-25 21:46 UTC, evan-gray commented on watcher/src/watchers/Watcher.ts
> +      if (this.chain === 'Berachain') {
maybe there could be a new field on the watcher for these cases like `SLEEP` or something? I think both cases could be covered by the below code.

2024-11-25 21:46 UTC, evan-gray commented on watcher/src/watchers/NearArchiveWatcher.ts
> +    return { vaasByBlock: response.vaasByBlock, optionalBlockHeight: response.lastBlockHeight };
couldn't this just return `response`?

2024-11-26 02:08 UTC, panoel commented on watcher/src/watchers/__tests__/parseVaa.test.ts
> +// import {
This file should not have been committed.  I used this to test some SDKv2 functionality.  It has been deleted.

2024-11-26 02:09 UTC, panoel commented on watcher/src/watchers/AlgorandWatcher.ts
> +    return { vaasByBlock, optionalBlockHeight: undefined };
Changed.

2024-11-26 02:09 UTC, panoel commented on watcher/src/watchers/AptosWatcher.ts
> +    return { vaasByBlock, optionalBlockHeight: undefined };
Changed.

2024-11-26 02:11 UTC, panoel commented on watcher/src/watchers/NearArchiveWatcher.ts
> +    return { vaasByBlock: response.vaasByBlock, optionalBlockHeight: response.lastBlockHeight };
Yes, changed.

2024-11-26 02:14 UTC, panoel commented on watcher/src/watchers/AlgorandWatcher.ts
> +    return { vaasByBlock, optionalBlockHeight: undefined };
Changed

2024-11-26 02:14 UTC, panoel commented on watcher/src/watchers/AptosWatcher.ts
> +    return { vaasByBlock, optionalBlockHeight: undefined };
Changed

2024-11-26 02:14 UTC, panoel commented on watcher/src/watchers/NearArchiveWatcher.ts
> +    return { vaasByBlock: response.vaasByBlock, optionalBlockHeight: response.lastBlockHeight };
Yes, changed.

2024-11-26 14:21 UTC, evan-gray approved these changes
I feel like there *might* be a better format for the `watch` loop :thinking: but what is there seems safe.

2024-11-26 14:28 UTC, merged