Acct: Add governed flag
wormhole-foundation/wormhole-dashboard pull request #82
Opened 2023-04-11 11:59 UTC by bruce-riley

2023-04-11 15:59 UTC, evan-gray requested changes
This is pretty good. The only downside to the component making the axios call is that when there are 4 items enqueued there end up being like 5 calls to `governor-stats` on the whole page. I think it might be best to hoist `const governorInfo = useCloudGovernorInfo();` to a shared component between `MainnetGovernor` and `Accountant` (`Main.tsx` could suffice for now). If it is in main, we would need to ensure that the hook doesn't fire off calls when not in mainnet. Alternatively, make a 'MainnetOnlyStuff' component that has everything from that ternary in `Main`

2023-04-11 15:59 UTC, evan-gray commented on dashboard/src/components/EnqueuedInGovChecker.tsx
> +      setVaaIsEnqueued(null);
this can be moved outside the async

2023-04-11 15:59 UTC, evan-gray commented on dashboard/src/components/EnqueuedInGovChecker.tsx
> +      setVaaIsEnqueued(isEnqueued);
when setting state in an async, always use a cancellable, otherwise there's a potential for your component to get destroyed and then call set state on a component that no longer exists. many other of the async hooks in this codebase use that pattern.

2023-04-17 16:48 UTC, bruce-riley commented
Reworked it to avoid the extra `useCloudGovernorInfo` calls.

2023-04-26 16:00 UTC, evan-gray approved these changes

2023-04-26 16:20 UTC, merged