Karura null blocks
wormhole-foundation/wormhole-dashboard pull request #96
Opened 2023-06-30 19:56 UTC by panoel

Sometimes Karura will reply with a null block on a perfectly valid block number.  We need to handle that.
Request:
```
    {
      jsonrpc: '2.0',
      id: '1',
      method: 'eth_getBlockByNumber',
      params: [ '0x461e9d', false ]
    }
```
Response:
```
 { id: '1', jsonrpc: '2.0', result: null } 
```

2023-07-01 19:33 UTC, evan-gray requested changes
one small optimization request. also not immediately sure why tests failed.

2023-07-01 19:33 UTC, evan-gray commented on watcher/src/watchers/EVMWatcher.ts
> +      if (typeof blockNumberOrTag === 'number' && blockNumberOrTag < latestBlockNumber - 1000) {
should the `typeof` part of this check be before calling `getFinalizedBlockNumber`? no point in calling if we won't use the result

2023-07-01 19:33 UTC, evan-gray commented on watcher/src/watchers/EVMWatcher.ts
> +    const latestBlockNumber = await this.getFinalizedBlockNumber();
it's kinda awkward that this would always get called twice now in the watcher loop. should we cache `latestBlockNumber`the way you did `lastTimestamp`? that would avoid that extra call in `getBlock` as well.

2023-07-03 16:38 UTC, panoel commented on watcher/src/watchers/EVMWatcher.ts
> +      if (typeof blockNumberOrTag === 'number' && blockNumberOrTag < latestBlockNumber - 1000) {
Fixed by making latestFinalizedBlockNumber a member variable.

2023-07-03 16:38 UTC, panoel commented on watcher/src/watchers/EVMWatcher.ts
> +    const latestBlockNumber = await this.getFinalizedBlockNumber();
Fixed by making latestFinalizedBlockNumber a member variable.

2023-07-06 13:22 UTC, evan-gray approved these changes

2023-07-06 13:27 UTC, merged